# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(default='null', max_length=6),
        ),
    ]
