# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_db', '0002_task_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
    ]
